# NOTE: This file is auto-generated, please do not modify

STATUS_ERROR_CODES = {
    0x00: "Success",
    0x01: "Unknown HCI Command",
    0x02: "Unknown Connection Identifier",
    0x03: "Hardware failure",
    0x05: "Authentication Failure",
    0x06: "PIN or Key Missing",
    0x07: "Memory Capacity Exceeded",
    0x08: "Connection Timeout",
    0x0C: "Command Disallowed",
    0x11: "Unsupported Feature Or Parameter Value",
    0x12: "Invalid HCI Command Parameters",
    0x13: "Remote User Terminated Connection",
    0x16: "Connection Terminated By Local Host",
    0x1A: "Unsupported Remote Feature / Unsupported LMP Feature",
    0x1F: "Unspecified Error",
    0x22: "LMP Response Timeout / LL Response Timeout",
    0x28: "Instant Passed",
    0x30: "Parameter out of range",
    0x38: "Host busy pairing",
    0x3A: "Controller Busy",
    0x3C: "Directed Advertising Timeout",
    0x3D: "Connection Terminated Due to MIC Failure",
    0x3E: "Connection Failed to be Established",
    0x40: "Unknown connection ID",
    0x41: "Failed",
    0x42: "Invalid parameters",
    0x43: "Busy",
    0x44: "Invalid length",
    0x45: "Pending",
    0x46: "Not allowed",
    0x47: "GATT error",
    0x48: "Out of memory",
    0x50: "Invalid CID",
    0x59: "Device in the blacklist",
    0x5A: "CSRK not found",
    0x5B: "IRK not found",
    0x5C: "Device not found in DB",
    0x5D: "Security DB full",
    0x5E: "Device not bonded",
    0x5F: "Insufficient encryption keysize",
    0x60: "Invalid handle",
    0x61: "Out of handles",
    0x62: "Invalid operation",
    0x63: "Characteristic already exists",
    0x64: "Insufficient resources",
    0x65: "Security permission error",
    0x70: "The address of the device could not be resolved using the IRK stored",
    0x82: "No valid slot",
    0x83: "Short window",
    0x84: "New interval failed",
    0x85: "Too large interval",
    0x86: "Slot length failed",
    0xF0: "Profile already initialized",
    0xF1: "Null parameter",
    0xFA: "Flash read failed",
    0xFB: "Flash write failed",
    0xFC: "Flash erase failed",
    0xFF: "Timeout",
}
